[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.13",
    "icecream>=2.1.4",
    "pydantic>=2.11.7",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.3",
]
